### ISSUE TITLE
logging HTTP status codes

### ISSUE THREAD

**Issue by sjparsons** [theanti9/PyCrawler#4]
I'm wondering what you think about logging the HTTP status codes on the URLs? 

200 / 301 / 302 / 403 / 400 / 500 ? 

http://www.w3.org/Protocols/HTTP/HTRESP.html

**Comment by theanti9** [comment]
Ah yes, that's a good idea. I don't really have time to work on this project right now, so I encourage you to fork it and if you'd like, when you are done, we can merge the changes into here. Thank you for the idea, though.
